### ISSUE TITLE
Generation Task - Specification Condition

### ISSUE THREAD

**Issue by ghost** [DriveWorks/SDK-Starter-Examples#2]
Let's add an example of how to implement a Generation Task Specification Condition.
Like that of [Check Value](https://docs.driveworkspro.com/Topic/GTCheckValue)

This takes advantage of the `ComponentTaskReleaseCondition` base class.

These conditions are evaluated at the time of releasing the components.

**Comment by thomasguillarddriveworks** [comment]
For clarity, this is one of these:
![image](https://user-images.githubusercontent.com/62140903/92134485-7d224f80-ee01-11ea-8107-69c0cfcc0f94.png)
