### ISSUE TITLE
Udf - Returning an error string

### ISSUE THREAD

**Issue by thomasguillarddriveworks** [DriveWorks/SDK-Starter-Examples#7]
Show how you can take advantage of error strings with a custom Udf.

An error string is formatted like so: `#PREFIX! Problem description.` and can be handled within a Specification with core Functions like `IsErrorString()` or `IfErrorString()`.

https://docs.driveworkspro.com/Topic/IsErrorString
https://docs.driveworkspro.com/Topic/IfErrorString

**Comment by MindaugasJarmaliunas-DriveWorks** [comment]
Pull request: https://github.com/DriveWorks/SDK-Starter-Examples/pull/22
